require:
  # - rubocop-jekyll
  - rubocop-md
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

# inherit_gem:
#  rubocop-jekyll: .rubocop.yml

AllCops:
  Exclude:
    - demo/_site/**/*
    - exe/**/*
    - vendor/**/*
    - jekyll_plugin_logger.gemspec
  NewCops: enable
  TargetRubyVersion: 2.6

Gemspec/DeprecatedAttributeAssignment:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

# Jekyll/NoPutsAllowed:
#   Exclude:
#     - spec/**/*

Layout/InitialIndentation:
  Exclude:
    - README.md

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 150

Lint/RedundantCopDisableDirective:
  Exclude:
    - jekyll_plugin_logger.gemspec

Metrics/BlockLength:
  Exclude:
    - jekyll_plugin_logger.gemspec
    - spec/**/*

Metrics/ClassLength:
  Exclude:
    - spec/**/*

Naming/FileName:
  Exclude:
    - Rakefile

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 15

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
